version: '3'

services:
  api:
    build: 
      dockerfile: ./dockerfile
      context: .
    image: node-api:v1.0
    container_name: node-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    command: npm run dev
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_DB_USERNAME: $MONGO_DB_USERNAME
      MONGO_DB_PASSWORD: $MONGO_DB_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_DB_COLLECTION: $MONGO_DB_COLLECTION
    ports:
      - 27017:27017
    volumes:
      - ./src/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD