on: push
name: deploy
jobs:
  deploy:
    name: deploy to aws
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
